### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by ghost** [ThisIsNoahEvans/IconsurAuto#1]
It is better to run the script using `sudo ./script.sh` instead of having everything in the script prepended with sudo

**Comment by ghost** [comment]
also you can *probably* change `/Users/noah/` to just `~/` and it will work without needing to change it but I'm not sure

**Comment by ThisIsNoahEvans** [comment]
the script goes in a folder that macOS runs itself so there's no option to run sudo on the script
and yeah good point, will change that. thanks!
